accounts/drf/urls.py
from django.urls import path

from rest_framework.authtoken import views

from .views import GetUsername, ObtainAuthToken,GetMyProfile

app_name = 'accounts_drf'

urlpatterns = [
    path('api-token-auth/', views.ObtainAuthToken.as_view()),
    path('getusername/<int:user_id>/', GetUsername.as_view() ),
    path('getprofile/', GetMyProfile.as_view() )
]

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
	path('others_dashboard/<int:user_id>/', views.others_dashboard, name='others_dashboard'),
	path('profile_update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile_update'),
	path('follow/', views.follow, name='follow'),
	path('unfollow/', views.unfollow, name='unfollow'),
	path('show_photo/<int:pk>/', views.show_photo, name='show_photo'),
	path('update_photo/<int:user_id>/<int:image_id>', views.update_photo, name='update_photo'),
	path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('requests/', views.follow_requests.as_view(), name='requests'),
	path('accept_request/', views.accept_request, name='accept_request'),
	path('follower_list/', views.follower_list.as_view(), name='follower_list'),
	path('reject_follow/', views.reject_follow, name='reject_follow'),

	path('following_list/', views.following_list.as_view(), name='following_list'),
	path('cancel_following/', views.cancel_following, name='cancel_following'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
	path('all_posts/', views.all_posts, name='all_posts'),

	path('<int:year>-<int:month>-<int:day>-<int:post_id>/', views.post_detail, name='post_detail'),
	path('add_post/<int:user_id>/', views.add_post, name='add_post'),
	path('post_delete/<int:user_id>/<int:post_id>/', views.post_delete, name='post_delete'),
	path('post_edit/<int:user_id>/<int:post_id>/', views.post_edit, name='post_edit'),
	path('add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
	path('like/<int:post_id>/', views.post_like, name='post_like'),
	path('dislike/<int:post_id>/', views.post_dislike, name='post_dislike'),

]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'shop'
urlpatterns = [
	path('shop/', views.shop_home, name='home'),
	path('shop/select_category/', views.select_category, name='select_category'),
	path('shop/<slug:category_slug>/', views.shop_home, name='category_filter'),
	path('add_product/<int:user_id>/', views.AddProduct.as_view(), name='add_product'),
	path('manage_products/<int:user_id>/', views.manage_products, name='manage_products'),
	path('product_reply/<int:product_id>/<int:comment_id>/', views.product_reply, name='product_reply'),
	path('product_like/<int:product_id>/', views.product_like, name='product_like'),
	path('product_remove/<int:pk>/', views.ProductDeleteView.as_view(), name='product_remove'),
	path('product_update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
	


	path('product_dislike/<int:product_id>/', views.product_dislike, name='product_dislike'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

single_message/urls.py
# chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name= 'single_message'
urlpatterns = [
    #path('', views.index, name='index'),
    #path('<str:room_name>/', views.room, name='room'),
    path('dual_room_id/<str:user_id>/', views.dual_room_id, name='dual_room_id'),
    path('dual_room/', views.dual_room, name='dual_room'),

    path('dual_room_email/<str:email>/', views.dual_room_email, name='dual_room_email'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

socsho/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('single_message/', include('single_message.urls', namespace='single_message')),
    path('', include('home.urls', namespace='home')),
    path('', include('posts.urls', namespace='posts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('search/', include('search.urls', namespace='search')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    
    #django rest framework urls
    path('drf/posts/', include('posts.drf.urls', namespace='post_drf')),
    path('drf/accounts/', include('accounts.drf.urls', namespace='accounts_drf')),
    path('drf/shop/', include('shop.drf.urls', namespace='shop_drf')),


    

]

accounts/drf/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from rest_framework.renderers import JSONRenderer

#from permissions import IsOwnerOrReadOnly
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from accounts.models import User

from .serializers import GetUsernameSerializer,AuthCustomTokenSerializer, GetMyProfileSerializer



class ObtainAuthToken(APIView):
    throttle_classes = ()
    permission_classes = ()
    parser_classes = (
        FormParser,
        MultiPartParser,
        JSONParser,
    )
    renderer_classes = (JSONRenderer,)

    def post(self, request):
        serializer = AuthCustomTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        content = {
            'token': unicode(token.key),
        }
        return Response(content)


class GetUsername(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self, request,user_id):
        queryset=get_object_or_404(User,pk=user_id)
        serializer=GetUsernameSerializer(queryset)
        return Response(serializer.data)


class  GetMyProfile(APIView):
    permission_classes = [IsAuthenticated,]
    def get(self,request):
        queryset=get_object_or_404(User,pk=request.user.id)
        serializer=GetMyProfileSerializer(queryset)
        return Response(serializer.data)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView
from django.urls import reverse
from django.http import JsonResponse
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.contrib import messages
from .models import User, Relation, ProfilePhoto
from posts.models import Post
from .forms import UserLoginForm, UserRegistrationForm, ProfileShowPhoto



def user_login(request):
	print (50*'L')
	print (request.user.is_authenticated)
	if request.user.is_authenticated:
		if request.GET.get('next'):
			return redirect(request.GET.get('next'))
		return redirect('accounts:dashboard', request.user.id)
	if request.method == 'POST':
		form = UserLoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, email=cd['email'], password=cd['password'])
			if user is not None:
				login(request, user)
				messages.success(request, 'you logged in successfully', 'success')
				if request.GET.get('next'):
					return redirect(request.GET.get('next'))
				return redirect('accounts:dashboard', user.id)
			else:
				messages.error(request, 'username or password is wrong', 'danger')
	else:
		form = UserLoginForm()
	return render(request, 'accounts/login.html', {'form':form})


def user_logout(request):
	logout(request)
	messages.success(request, 'you logged out successfully', 'success')
	return redirect('accounts:login')


def user_register(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = User.objects.create_user(cd['email'], cd['full_name'], cd['password'])
			user.save()
			messages.success(request, 'you registered successfully', 'success')
			return redirect('accounts:dashboard', user.id)
	else:
		form = UserRegistrationForm()
	return render(request, 'accounts/register.html', {'form':form})

@login_required
def others_dashboard(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	posts = Post.objects.filter(user=user)
	is_following = False
	is_requested= False
	num_follower=Relation.objects.filter(to_user=user, accepted=True).count()
	num_following=Relation.objects.filter(from_user=user, accepted=True).count()
	num_requests=0
	if request.user is not None :
		
		relation = Relation.objects.filter(from_user=request.user, to_user=user).last()
		print (relation) 
		if relation != None :
			print (relation.accepted)
			if relation.accepted :
				is_following = True
			else: 
				is_requested = True
	
	print (is_requested)
	return render(request, 'accounts/dashboard.html', {'user':user, 'posts':posts, 
														'num_requests':num_requests, 'is_requested':is_requested,
														 'is_following':is_following, 'num_follower':	num_follower, 
														 'num_following': num_following })

@login_required
def user_dashboard(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	posts = Post.objects.filter(user=user)
	self_dash = True
	
	print('******************************************************')
	
	num_follower=Relation.objects.filter(to_user=user, accepted=True).count()
	num_following=Relation.objects.filter(from_user=user, accepted=True).count()
	num_requests=0
	
	return render(request, 'accounts/dashboard.html', {'user':user, 'posts':posts, 'self_dash':self_dash, 
													'num_follower':	num_follower,  'num_following': num_following })


class ProfileUpdate(UpdateView):
	model = User
	fields = ('full_name', 'bio', 'age', 'status')
	template_name = 'accounts/update_profile.html'
	
	def get_success_url(self):
           pk = self.kwargs["pk"]
           return reverse("accounts:dashboard", kwargs={"user_id": pk})


@login_required
def follow(request):
	if request.method == 'POST':
		user_id = request.POST['user_id']
		
		following = get_object_or_404(User, pk=user_id)
		if following.private :
			send_request = Relation.objects.create(from_user=request.user, to_user=following, accepted= False)
			send_request.save()
			return JsonResponse({'status':'private'})
		check_relation = Relation.objects.filter(from_user=request.user, to_user=following)
		if check_relation.exists():
			return JsonResponse({'status':'exists'})			
		else:
			Relation(from_user=request.user, to_user=following).save()
			return JsonResponse({'status':'ok'})
			


@login_required
def unfollow(request):
	if request.method == 'POST':
		user_id = request.POST['user_id']
		following = get_object_or_404(User, pk=user_id)
		check_relation = Relation.objects.filter(from_user=request.user, to_user=following)
		if check_relation.exists():
			check_relation.delete()
			return JsonResponse({'status':'ok'})
		else:
			return JsonResponse({'status':'notexists'})

@login_required
def  show_photo(request, pk):
	user = get_object_or_404(User, pk= pk)
	profile_photos=ProfilePhoto.objects.filter(user=user)
	self_dash= False
	if user == request.user :
		self_dash=True
		if request.method == 'POST':
			form = ProfileShowPhoto(request.POST,request.FILES)
			if form.is_valid():
				# image_path = user.image.path
				# if os.path.exists(image_path):
				# 	os.remove(image_path)
				
				pfm=form.save(commit=False)
				pfm.user=user
				pfm.save()
				profile_photo=ProfilePhoto.objects.filter(user=user).last()
				user.image=profile_photo.image
				user.save()
				messages.success(request, 'your image updated successfully', 'info')

			return redirect('accounts:show_photo', user.id)
		
	form = ProfileShowPhoto()
	return render(request,'accounts/show_photo.html', {'self_dash':self_dash, 'user': user, 'form': form, 'profile_photos': profile_photos} )

@login_required
def update_photo(request, user_id, image_id):
	user = get_object_or_404(User, pk= user_id)
	if user == request.user :
		profile_photo=get_object_or_404(ProfilePhoto,pk=image_id)
		user.image=profile_photo.image
		user.save()
	return redirect('accounts:dashboard', user.id)


class UserPasswordResetView(auth_views.PasswordResetView):
	template_name = 'accounts/password_reset_form.html'
	success_url = reverse_lazy('accounts:password_reset_done')
	email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
	template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
	template_name = 'accounts/password_reset_confirm.html'
	success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
	template_name = 'accounts/password_reset_complete.html'


class follow_requests(LoginRequiredMixin, View):
	def get(self,request):
		follow_requests=Relation.objects.filter(to_user=request.user, accepted=False)
		
		return render(request,'accounts/requests.html', {'follow_requests': follow_requests,} )

def accept_request(request):
	
		if request.method == 'POST':

			user_id = request.POST['user_id']
			follower = get_object_or_404(User, pk=user_id)
			print (user_id)
			check_relation = Relation.objects.filter(from_user=follower, to_user=request.user).last()
			print(50*'f')
			print (check_relation.from_user)
			if check_relation:
				check_relation.accepted = True
				check_relation.save()
				print("relation exist")
				return JsonResponse({'status':'ok'})
			else:
				return JsonResponse({'status':'notexists'})



class follower_list(LoginRequiredMixin, View):
	def get(self,request):
		followers=Relation.objects.filter(to_user=request.user, accepted=True)
		
		return render(request,'accounts/follower_list.html', {'followers': followers,} )


def reject_follow(request):
	
		if request.method == 'POST':

			user_id = request.POST['user_id']
			follower = get_object_or_404(User, pk=user_id)
			print (user_id)
			check_relation = Relation.objects.filter(from_user=follower, to_user=request.user).last()
			print(50*'f')
			print (check_relation.from_user)
			if check_relation:
				check_relation.delete()
				print("relation deleted")
				return JsonResponse({'status':'ok'})
			else:
				return JsonResponse({'status':'notexists'})


class following_list(LoginRequiredMixin, View):
	def get(self,request):
		followeing=Relation.objects.filter(from_user=request.user)
		print(followeing)
		return render(request,'accounts/followeing_list.html', {'followeing': followeing,} )

def cancel_following(request):
	
		if request.method == 'POST':

			user_id = request.POST['user_id']
			follower = get_object_or_404(User, pk=user_id)
			print (user_id)
			check_relation = Relation.objects.filter(to_user=follower, from_user=request.user).last()
			print(50*'f')
			print (check_relation.from_user)
			if check_relation:
				check_relation.delete()
				print("relation deleted")
				return JsonResponse({'status':'ok'})
			else:
				return JsonResponse({'status':'notexists'})

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% csrf_token %}

{% block user_email %} {{ request.user.email }} Profile {% endblock %}

{% block js_files %}
    <script src="{% static 'accounts/js/scripts.js' %}"></script>
{% endblock %}

{% block content %}
    {% if self_dash %}
        <table>
            <li><a href="{% url 'posts:add_post' request.user.id %}">Add post</a></li>
            <li><a href="{% url 'shop:add_product' request.user.id %}">Add Product</a></li>
            <li><a href="{% url 'shop:manage_products' request.user.id %}">Manage product </a></li>

            <li><a href="{% url 'accounts:profile_update' request.user.id %}">Edit Profile</a></li>
        </table>
    {% endif %}

    <div class="card text-center" style="width: 18rem; display:inline-block">
        {% thumbnail user.image "300x300" as img %}
            <a href="{% url 'accounts:show_photo' user.id %}">
                <img  src="{{ img.url }}" class="card-img-top">
            </a>
        {% endthumbnail %}        
    </div>

    <h4 class="text-center">{{ user.email|capfirst }}</h4>
    <p class="text-center">{{ user.bio }}</p>
    {% if user.age %}
        <p class="text-center">{{ user.age }} years old</p>
    {% endif %}

    

    
    {% if request.user.id != user.id and is_following  %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-warning text-center mx-auto">unfollow</button>
    {% elif request.user.id != user.id and is_requested %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-warning text-center mx-auto">follow request</button>
    {% elif request.user.id != user.id %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-primary text-center mx-auto">follow</button>
    {% endif %}
    <a href="{% url 'accounts:following_list' %}"  >{{num_following}}  are following </p>
    <a href="{% url 'accounts:follower_list' %}" >{{num_follower}} are followe  </p>
    
    {% if request.user.id == user.id  %}
        <a href="{% url 'accounts:requests' %}" >{{num_requests}} follow requests </a>
    {% endif %}
    {% if request.user.id != user.id  %}
        <form action="{% url 'single_message:dual_room_id' user.id %}" method="post" class="btn btn-primary text-center mx-auto">
            {% csrf_token %}
        
            <input type="submit"  value="Message" class="btn btn-primary text-center mx-auto">
        </form>
    {% endif %}
    <br/><br/><br/>
    {% for post in posts %}
        <div class="card">
            <p class="card-body"><a href="{{ post.get_absolute_url }}">{{ post.body }}</a></p>
        </div>
    {% empty %}
        <p>This user has no posts</p>
    {% endfor %}
{% endblock %}

accounts/templates/accounts/followeing_list.html
{% extends 'base.html' %}
{% load static %}

{% block js_files %}
    <script src="{% static 'accounts/js/cancel_following.js' %}"></script>
    <script src="{% static 'accounts/js/scripts.js' %}"></script>
{% endblock %}
{% block content %}
    <p>following</p>
    <ul>
        {% for follower in followeing  %}
            {% if not  follower.accepted %}
                <li><span>{{follower.to_user.email}} </span></li>
                <li>
                <button id="cancel_following" data-id="{{ follower.to_user.id }}" style="display:block" class="cancel_following btn btn-warning text-center mx-auto">cancel request following {{ follower.from_user.id }} </button>
                </li>
            {% else %}
                <li>
                    <span>{{follower.to_user.email}} </span>
                </li>
                <li>
                    <button id="cancel_following" data-id="{{ follower.to_user.id }}" style="display:block" class="cancel_following btn btn-warning text-center mx-auto">cancel following {{ follower.from_user.id }} </button>
                </li>
            {% endif %}     
        
        {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/follower_list.html
{% extends 'base.html' %}
{% load static %}

{% block js_files %}
    <script src="{% static 'accounts/js/reject_follow.js' %}"></script>
{% endblock %}
{% block content %}
    <p>followrs</p>
    
    <ul>
        {% for follower in followers  %}
            {% if  follower.accepted %}


                <li>
                <span>{{follower.from_user.email}} </span>

                </li>
                <li>
                <button id="reject_follow" data-id="{{ follower.from_user.id }}" style="display:block" class="reject_follow btn btn-warning text-center mx-auto">reject_follow {{ follower.from_user.id }} </button>

                </li>
                     
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <p>Login page</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
    <p><a class="nav-item nav-link active" href="{% url 'accounts:reset_password' %}">Reset password</a> </p>
{% endblock %}

accounts/templates/accounts/others_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% csrf_token %}

{% block user_email %} {{ request.user.email }} Profile {% endblock %}

{% block js_files %}
    <script src="{% static 'accounts/js/scripts.js' %}"></script>
{% endblock %}

{% block content %}


    <div class="card text-center" style="width: 18rem; display:inline-block">
        {% thumbnail user.image "300x300" as img %}
            <a href="{% url 'accounts:show_photo' user.id %}">
                <img  src="{{ img.url }}" class="card-img-top">
            </a>
        {% endthumbnail %}        
    </div>

    <h4 class="text-center">{{ user.email|capfirst }}</h4>
    <p class="text-center">{{ user.bio }}</p>
    {% if user.age %}
        <p class="text-center">{{ user.age }} years old</p>
    {% endif %}

    

    
    {% if request.user.id != user.id and is_following  %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-warning text-center mx-auto">unfollow</button>
    {% elif request.user.id != user.id and is_requested %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-warning text-center mx-auto">follow request</button>
    {% elif request.user.id != user.id %}
        <button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-primary text-center mx-auto">follow</button>
    {% endif %}
    <a href="{% url 'accounts:following_list' %}"  >{{num_following}}  are following </p>
    <a href="{% url 'accounts:follower_list' %}" >{{num_follower}} are follower  </p>
    
    
    {% if request.user.id != user.id  %}
        <form action="{% url 'single_message:dual_room_id' user.id %}" method="post" class="btn btn-primary text-center mx-auto">
            {% csrf_token %}
        
            <input type="submit"  value="Message" class="btn btn-primary text-center mx-auto">
        </form>
    {% endif %}
    <br/><br/><br/>
    {% for post in posts %}
        <div class="card">
            <p class="card-body"><a href="{{ post.get_absolute_url }}">{{ post.body }}</a></p>
        </div>
    {% empty %}
        <p>This user has no posts</p>
    {% endfor %}
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/show_photo.html
{% extends 'base.html' %}

{% block js_files %}
<script>
    var slideIndex = 1;
    showSlides(slideIndex);
    
    function plusSlides(n) {
      showSlides(slideIndex += n);
    }
    
    function currentSlide(n) {
      showSlides(slideIndex = n);
    }
    
    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}    
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";  
      }
      for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
    }
    </script>
{% endblock %}
{% block css_files %}
<style>
    * {box-sizing: border-box}
    body {font-family: Verdana, sans-serif; margin:0}
    .mySlides {display: none}
    img {vertical-align: middle;}
    
    /* Slideshow container */
    .slideshow-container {
      max-width: 500px;
      height: 500px;
      position: relative;
      margin: auto;
      overflow: hidden;
    }
    
    /* Next & previous buttons */
    .prev, .next {
      cursor: pointer;
      position: absolute;
      top: 50%;
      width: auto;
      padding: 16px;
      margin-top: -22px;
      color: white;
      font-weight: bold;
      font-size: 18px;
      transition: 0.6s ease;
      border-radius: 0 3px 3px 0;
      user-select: none;
    }
    
    /* Position the "next button" to the right */
    .next {
      right: 0;
      border-radius: 3px 0 0 3px;
    }
    
    /* On hover, add a black background color with a little bit see-through */
    .prev:hover, .next:hover {
      background-color: rgba(0,0,0,0.8);
    }
    
    /* Caption text */
    .text {
      color: #f2f2f2;
      font-size: 15px;
      padding: 8px 12px;
      position: absolute;
      bottom: 8px;
      width: 100%;
      text-align: center;
    }
    
    /* Number text (1/3 etc) */
    .numbertext {
      color: #f2f2f2;
      font-size: 12px;
      padding: 8px 12px;
      position: absolute;
      top: 0;
    }
    
    /* The dots/bullets/indicators */
    .dot {
      cursor: pointer;
      height: 15px;
      width: 15px;
      margin: 0 2px;
      background-color: #bbb;
      border-radius: 50%;
      display: inline-block;
      transition: background-color 0.6s ease;
    }
    
    .active, .dot:hover {
      background-color: #717171;
    }
    
    /* Fading animation */
    .fade {
      -webkit-animation-name: fade;
      -webkit-animation-duration: 5s;
      animation-name: fade;
      animation-duration: 5s;
    }
    
    @-webkit-keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    @keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    /* On smaller screens, decrease text size */
    @media only screen and (max-width: 300px) {
      .prev, .next,.text {font-size: 11px}
    }
    </style>
{% endblock %}
{% block content %}
  
    
    
    <div class="slideshow-container">
        {% for  profile_photo in profile_photos %}
            <div class="mySlides ">
                <div class="numbertext">1 / {{profile_photos.count}} </div>
                {% if  self_dash %}<a href="{% url 'accounts:update_photo' user.id  profile_photo.id %}">{% endif %}
                  <img src=" {{profile_photo.image.url}} " style=" height:auto; width:100%;">
                {% if  self_dash %}</a>{% endif %}
                <div class="text">Caption Text</div>
            </div>
        {% endfor %}
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    
    </div>
    <br>
    
    <div style="text-align:center">
        {% for  profile_photo in profile_photos %}

            <span class="dot" onclick="currentSlide('{{ forloop.counter }}' )"></span> 
        {% endfor %}
        <br>
        {% if  self_dash %}
          <img src="{{ user.image.url }}" alt="" width="400px" height="400px">
          <form action="" method="post" enctype="multipart/form-data" >
              {% csrf_token %}
              {{ form }}
              <input type="submit" value="Update">          
          </form>
        {% endif %}
      
    </div>
    
    
    
{% endblock %}