accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
	path('others_dashboard/<int:user_id>/', views.others_dashboard, name='others_dashboard'),
	path('profile_update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile_update'),
	path('follow/', views.follow, name='follow'),
	path('unfollow/', views.unfollow, name='unfollow'),
	path('show_photo/<int:pk>/', views.show_photo, name='show_photo'),
	path('update_photo/<int:user_id>/<int:image_id>', views.update_photo, name='update_photo'),
	path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('requests/', views.follow_requests.as_view(), name='requests'),
	path('accept_request/', views.accept_request, name='accept_request'),
	path('follower_list/', views.follower_list.as_view(), name='follower_list'),
	path('reject_follow/', views.reject_follow, name='reject_follow'),

	path('following_list/', views.following_list.as_view(), name='following_list'),
	path('cancel_following/', views.cancel_following, name='cancel_following'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'home'
urlpatterns = [
	path('', views.all_home, name='all_home'),
	path('/<slug:category_slug>/', views.all_home, name='category_filter'),

	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/drf/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop_drf'
urlpatterns = [
    path('products/', views.AllProducts.as_view() , name='AllProduts'),
    path('product/<int:pk>/', views.ProductDetail.as_view() , name='ProductDetail'),
    path('category/',views.AllCategories.as_view())

    # path('<int:product_id>/', views.ProductDetail.as_view() , name='ProductDetail'),
    # path('comment/', views.AddComment.as_view() , name='AddComment'),
    # path('like/<int:product_id>/', views.PostLike.as_view() , name='PostLike'),
    # path('<int:product_id>/', views.PostLike.as_view() , name='PostLike'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'shop'
urlpatterns = [
	path('shop/', views.shop_home, name='home'),
	path('shop/select_category/', views.select_category, name='select_category'),
	path('shop/<slug:category_slug>/', views.shop_home, name='category_filter'),
	path('add_product/<int:user_id>/', views.AddProduct.as_view(), name='add_product'),
	path('manage_products/<int:user_id>/', views.manage_products, name='manage_products'),
	path('product_reply/<int:product_id>/<int:comment_id>/', views.product_reply, name='product_reply'),
	path('product_like/<int:product_id>/', views.product_like, name='product_like'),
	path('product_remove/<int:pk>/', views.ProductDeleteView.as_view(), name='product_remove'),
	path('product_update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
	


	path('product_dislike/<int:product_id>/', views.product_dislike, name='product_dislike'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socsho/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('single_message/', include('single_message.urls', namespace='single_message')),
    path('', include('home.urls', namespace='home')),
    path('', include('posts.urls', namespace='posts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('search/', include('search.urls', namespace='search')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    
    #django rest framework urls
    path('drf/posts/', include('posts.drf.urls', namespace='post_drf')),
    path('drf/accounts/', include('accounts.drf.urls', namespace='accounts_drf')),
    path('drf/shop/', include('shop.drf.urls', namespace='shop_drf')),


    

]

shop/models.py
from email.mime import image
from itertools import product
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey

from accounts.models import User




class Category(MPTTModel): # categories
	name = models.CharField(
		verbose_name=_("Category Name"), 
		help_text=_("Required and unique"),
		max_length=255,	
		unique=True
		)
	slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
	parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
	is_active = models.BooleanField(default=True)

	class MPTTMeta:
		order_insertion_by = ["name"]

	class Meta:
		verbose_name = _("Category")
		verbose_name_plural = _("Categories")

	def get_absolute_url(self):
		return reverse("home:category_filter", args=[self.slug])

	def __str__(self):
		return self.name

class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    category = models.ForeignKey(Category, on_delete=models.RESTRICT, related_name='C_product_secification')
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
	category = models.ForeignKey(Category, on_delete=models.RESTRICT)
	title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
	description = models.TextField(verbose_name=_("description"), help_text=_("Not Required"), blank=True)
	slug = models.SlugField(max_length=255)
	price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
	discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
	is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
	created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
	users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

	class Meta:
		ordering = ("-created_at",)
		verbose_name = _("Product")
		verbose_name_plural = _("Products")

	def get_absolute_url(self):
		return reverse("shop:product_detail", args=[self.slug])

	def __str__(self):
		return self.title

	def likes_count(self):
		return self.prodvote.count()

	def user_can_like(self, user):
		user_like = user.produservote.all()
		qs = user_like.filter(product=self)
		if qs.exists():
			return True
		return False


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='P_product_specificatiob_value')
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")


class ProdComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uProdComment')
    product=models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, related_name='PrProdComment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rProdComment')
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

    class Meta:
        ordering = ('-created',)


class ProdVote(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='prodvote')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='produservote')

    def __str__(self):
        return f'{self.user} liked {self.product}'


class ProductPhoto(models.Model):
	product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name="p_photo")
	image = models.ImageField(upload_to='products/%Y/%m/%d/')
	created = models.DateTimeField(auto_now_add=True)


class ProducVideo(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_video")
    Video = models.FileField(
        verbose_name=_("Video"),
        help_text=_("Upload a product video"),
        upload_to="video/",
        default="video/default.mp4",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = _("Product video")
        verbose_name_plural = _("Product video")

shop/forms.py
from django import forms
from .models import Product, Category, ProdComment, ProductPhoto, ProductSpecification, ProducVideo
from mptt.forms import TreeNodeChoiceField

class AddProductForm(forms.ModelForm):
   

    category_choice= Category.objects.all()
    category = TreeNodeChoiceField(queryset=category_choice,  widget=forms.Select(attrs={'class': 'form-control'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'size':30}))

    class Meta:
        model = Product
        fields = (  'title' , 'category', 'description', 'price', 'discount_price' )


  
class AddProductPhotoForm(forms.ModelForm):
    image = forms.ImageField()
    class Meta:
        model = ProductPhoto
        fields = ('image',)



class AddProductCommentForm(forms.ModelForm):
    class Meta:
        model = ProdComment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }
        error_messages = {
            'body': {
                'required': 'این فیلد اجباری است',
            }
        }
        help_texts = {
            'body': 'max 400 char'
        }

class AddReplyProductForm(forms.ModelForm):
        class Meta:
            model = ProdComment
            fields = ('body',)

shop/drf/views.py
from unicodedata import category
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
#from permissions import IsOwnerOrReadOnly
from django.utils.text import slugify
from django.shortcuts import get_object_or_404

from .serializers import ProductSerializer, CategorySerializer, ProductDetailSerializer
from shop.models import Product, ProductImage, Category,ProductSpecification, ProductSpecificationValue
from posts.models import Post


class AllCategories(APIView):

    def get(self, request):
        categories=Category.objects.all()
        srz_data=CategorySerializer(instance=categories, many=True)
        return Response(srz_data.data)


class AllProducts(APIView):

    def get(self, request):
        products=Product.objects.all()
        srz_data=ProductSerializer(instance=products,many=True)
        return Response(srz_data.data)

    def post(self, request):
        queryset = Product.objects.all()
        parser_classes = [MultiPartParser, FormParser]
        permission_classes = [IsAuthenticated,]
        srz_data = ProductSerializer(data=request.data)
        if srz_data.is_valid():
            slug = slugify(request.data['description'][:30], allow_unicode=True)
            product=srz_data.save(user=request.user, slug=slug)
            try:
                # try to get and save images (if any)
                images_data = dict((request.FILES).lists()).get('images', None)
                is_feature=True
                for image in images_data:
                    ProductImage.objects.create(product=product, image=image,is_feature=is_feature)
                    is_feature=False
            except:
                # if no images are available - create using default image
                
                ProductImage.objects.create(product=product)
            specc_list=ProductSpecification.objects.filter(category=request.data['category'])
            for sp in specc_list:
                print(10*'-pNme--')
                print(sp.name)
                if sp.name in request.data:
                    specification_value=request.data[sp.name]
                    print(10*'spNme--')
                    print(sp.name)
                    ProductSpecificationValue.objects.create(product=product, specification=sp, value=specification_value)

                    

            post=Post.objects.create(user=request.user, body=request.data['description'], slug = slug, image=image)

            return Response(srz_data.data, status=status.HTTP_201_CREATED)   
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductDetail(APIView):
    def get(self,request,pk):
        product=get_object_or_404(Product,pk=pk)
        srz_data=ProductDetailSerializer(instance=product)
        return Response(srz_data.data)

shop/templates/shop/add_product.html
{% extends 'base.html' %}
{% load mptt_tags %}
{% block js_files %}
<script>
 $(document).on("change","#id_category",function(){
     
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
 
    category_slug = $(this).val();
    
    $.ajax({
        url: '/shop/select_category/',
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        data: {
            'category_slug': category_slug ,
        },
        success: function(data){
            $( ".ajax_input" ).empty();
            $.each(data, function(key, val) {
                var BR = document.createElement('Br');
                document.getElementsByClassName('ajax_input')[0].appendChild(BR);   
                var elem2 = document.createElement('label');
                elem2.innerHTML =val.name; 
                document.getElementsByClassName('ajax_input')[0].appendChild(elem2);                                
                $('<input>').attr({
                   type: 'text',                   
                   id: val.name ,
                   name: val.name
               }).appendTo('#ajax_input');
               
            });            
        }
    });
});
</script>
{% endblock %}
{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        
        {% csrf_token %}
        {{ form.as_p }}
        <div class="ajax_input" id="ajax_input" >

        </div>
        <input type="file" name="images" class="form-control-file" id="note-image" multiple>
        <input type="file" name="videos" class="form-control-file" id="note-video" multiple>
        <input type="submit" value="Add Product">
    </form>
    
{% endblock %}

shop/templates/shop/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular</b> products purchased</div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'home:all_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card border-0">
            {% for image in product.product_image.all %}
            {% if image.is_feature%}
            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
            {% endif %}
            {% endfor %}
            <div class="card-body px-0">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">£{{product.regular_price}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

shop/templates/shop/manage_product.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
   

    <br/><br/><br/>

    {% for product in products %}
        <div class="card" style="width: 18rem; display:inline-block">
            {% thumbnail product.image "300x300" as img %}
            <img src="{{ img.url }}" class="card-img-top">
            {% endthumbnail %}
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

shop/templates/shop/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% csrf_token %}

{% block js_files %}
<script>
    $(document).ready(function(){
      $(".Reply_class").click(function(){
        $(this).parent().next().toggle();
       });
      
    });
    
</script>
<script src="{% static 'accounts/js/slide_show.js' %}"></script>

{% endblock %}
{% block css_files %}
<style >
  * {box-sizing: border-box}
    body {font-family: Verdana, sans-serif; margin:0}
    .mySlides {display: none}
    img {vertical-align: middle;}
    
    /* Slideshow container */
    .slideshow-container {
      max-width: 500px;
      height: 500px;
      position: relative;
      margin: auto;
      overflow: hidden;
    }
    
    /* Next & previous buttons */
    .prev, .next {
      cursor: pointer;
      position: absolute;
      top: 50%;
      width: auto;
      padding: 16px;
      margin-top: -22px;
      color: white;
      font-weight: bold;
      font-size: 18px;
      transition: 0.6s ease;
      border-radius: 0 3px 3px 0;
      user-select: none;
    }
    
    /* Position the "next button" to the right */
    .next {
      right: 0;
      border-radius: 3px 0 0 3px;
    }
    
    /* On hover, add a black background color with a little bit see-through */
    .prev:hover, .next:hover {
      background-color: rgba(0,0,0,0.8);
    }
    
    /* Caption text */
    .text {
      color: #f2f2f2;
      font-size: 15px;
      padding: 8px 12px;
      position: absolute;
      bottom: 8px;
      width: 100%;
      text-align: center;
    }
    
    /* Number text (1/3 etc) */
    .numbertext {
      color: #f2f2f2;
      font-size: 12px;
      padding: 8px 12px;
      position: absolute;
      top: 0;
    }
    
    /* The dots/bullets/indicators */
    .dot {
      cursor: pointer;
      height: 15px;
      width: 15px;
      margin: 0 2px;
      background-color: #bbb;
      border-radius: 50%;
      display: inline-block;
      transition: background-color 0.6s ease;
    }
    
    .active, .dot:hover {
      background-color: #717171;
    }
    
    /* Fading animation */
    .fade {
      -webkit-animation-name: fade;
      -webkit-animation-duration: 5s;
      animation-name: fade;
      animation-duration: 5s;
    }
    
    @-webkit-keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    @keyframes fade {
      from {opacity: .4} 
      to {opacity: 1}
    }
    
    /* On smaller screens, decrease text size */
    @media only screen and (max-width: 300px) {
      .prev, .next,.text {font-size: 11px}
    }
</style>
{% endblock %}

{% block content %}
    <h3>{{ product.name }}</h3>
    <small>{{ product.created }}</small>
    <p>{{ product.price }} Toman</p><br/>
    {% for  psv in productspecificationvalue %}
      <p>{{psv.specification}} : {{psv.value}} </p>
    {% endfor %}
    
    <div class="slideshow-container">
        {% for  image in images %}
            <div class="mySlides ">
                <div class="numbertext">1 / {{images.count}} </div>
                    <img src=" {{image.image.url}} " style=" height:auto; width:100%;">
                
                <div class="text">Caption Text</div>
            </div>
        {% endfor %}
        {% for  video in product.product_video.all %}
            <div class="mySlides ">
                <div class="numbertext">1 / {{videos.count}} </div>
                    <video width='400' controls>
                        <source src=' {{video.video.url}}' type='video/mp4'>
                        Your browser does not support the video tag.
                    </video>
                <div class="text">Caption Text</div>
            </div>
        {% endfor %}
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    
    </div>
    <br>
    
    <div style="text-align:center">
        {% for  image in images %}
            <span class="dot" onclick="currentSlide('{{ forloop.counter }}' )"></span>
        {% endfor %}
        {% for  video in product.product_video.all %}
            <span class="dot" onclick="currentSlide('{{ forloop.counter }}' )"></span>
        {% endfor %}
        <br>
    </div>
    
    <p>{{ product.description }}</p><br/><br/>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form_cart }}
        <input type="submit" value="Add to cart">
    </form>

    {% if request.user.is_authenticated %}
        {% if not can_like %}
            <a href="{% url 'shop:product_like' product.id %}" class="btn btn-primary {% if can_like %} disabled {% endif %} col-md-2">Like {{ product.likes_count }}</a>
        {% else %}
            <div class="btn btn-primary col-md-3">You Liked and {{ product.likes_count }} others</div>
            <div>
                <a href="{% url 'shop:product_dislike' product.id %}" class="btn btn-warning  col-md-1">DissLike </a>
            </div>
        {% endif %}
    {% endif %}
    <br/>
    {% if self_dash %}
      <div>
        <a href="{% url 'shop:product_update' product.id %}" class="btn btn-primary  col-md-1">Edit </a>

        <a href="{% url 'shop:product_remove' product.id %}" class="btn btn-warning  col-md-1">Remove </a>

      </div>
    {% endif %}
    {% if request.user.is_authenticated %}
    <form action="" method="post" novalidate class="col-md-6">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
    {% else %}
        <p>only logged in users can send comments</p>
    {% endif %}<br/><br/><br/>

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-body">{{ comment.body }}</p>
            {% if request.user.is_authenticated %}
            <div  class="card-header"><a href="{% url 'accounts:dashboard' comment.user.id  %}"> {{comment.user }} </a><div  class="Reply_class btn btn-primary col-md-1">reply</div></div>

            <div class="card-body" style="display:none" id="reply_id">
                <form action="{% url 'shop:product_reply' product.id comment.id %}" method="post">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="Send reply">
                </form>
            </div>
            {% else %}
                <p>you have to login to send reply</p>
            {% endif %}
            {% for reply in comment.rProdComment.all %}
                <p class="bg-primary text-white p-3 m-5">{{ reply.user }} <br/> {{ reply.body }}</p>
            {% endfor %}
        </div><br/>
    {% empty %}
        <p>There is no comment</p>
    {% endfor %}
{% endblock %}

shop/templates/shop/product_form.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

shop/templates/shop/shop_home.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
    {% for category in categories %}

        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu">
                {% for sub in category.scategory.all %}
                    <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <br/><br/><br/>

    {% for product in products %}
        <div class="card" style="width: 18rem; display:inline-block">
            {% thumbnail product.image "300x300" as img %}
            <img src="{{ img.url }}" class="card-img-top">
            {% endthumbnail %}
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}