accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
	path('others_dashboard/<int:user_id>/', views.others_dashboard, name='others_dashboard'),
	path('profile_update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile_update'),
	path('follow/', views.follow, name='follow'),
	path('unfollow/', views.unfollow, name='unfollow'),
	path('show_photo/<int:pk>/', views.show_photo, name='show_photo'),
	path('update_photo/<int:user_id>/<int:image_id>', views.update_photo, name='update_photo'),
	path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('requests/', views.follow_requests.as_view(), name='requests'),
	path('accept_request/', views.accept_request, name='accept_request'),
	path('follower_list/', views.follower_list.as_view(), name='follower_list'),
	path('reject_follow/', views.reject_follow, name='reject_follow'),

	path('following_list/', views.following_list.as_view(), name='following_list'),
	path('cancel_following/', views.cancel_following, name='cancel_following'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'home'
urlpatterns = [
	path('', views.all_home, name='all_home'),
	path('/<slug:category_slug>/', views.all_home, name='category_filter'),

	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socsho/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('single_message/', include('single_message.urls', namespace='single_message')),
    path('', include('home.urls', namespace='home')),
    path('', include('posts.urls', namespace='posts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('search/', include('search.urls', namespace='search')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    
    #django rest framework urls
    path('drf/posts/', include('posts.drf.urls', namespace='post_drf')),
    path('drf/accounts/', include('accounts.drf.urls', namespace='accounts_drf')),
    path('drf/shop/', include('shop.drf.urls', namespace='shop_drf')),


    

]

templates/inc/footer.html
<style>
    .footer{
        position: fixed; 
        bottom: 0;
    left: 0;
    right: 0;
    height:70px;
    }
    .chatmenu-btn {
    background-color: #7e32d4;
    color: white;
    padding: 8px;
    font-size: 20px;
    font-weight: bolder;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    border: none;
    width: 160px;
    
    }
    .chatdropdown-menu {
    position: relative;
    display: inline-block;
    padding-top: 0px;
    }
    .chatmenu-content {
    display: none;
    position: absolute;
    bottom: 50px;
    background-color: #7df3f3;
    min-width: 100px;
    z-index: 1;
    }
    .links {
        color: rgb(255, 255, 255);
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        font-size: 18px;
        font-weight: bold;
        border-bottom: 1px solid black;
    }
    .links:hover {
        background-color: rgb(8, 107, 46);
    }
    .chatdropdown-menu:hover .chatmenu-content {
        display: block;
    }
    .chatdropdown-menu:hover .chatmenu-btn {
        
        background-color: #3e8e41;
    }
</style>
 
<nav class="footer navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav" >
        
        <div class="nav-item nav-link active" style="align-self: flex-end ; color:mediumturquoise;">{{ request.user.email }}</div>
        <div class="chatdropdown-menu">
            
            <button type="button" class="chatmenu-btn" ><a id="button_chat"  >chat list</a></button>
            <div id="dropdown_chat_list" class="chatmenu-content" >
                
            </div>
        </div>
    </div>
    
</nav>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'home:all_home' %}">All</a></li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
              <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
            </li>
            {% endfor %}
        </ul>
        <a class="nav-item nav-link active" href="{% url 'home:all_home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'accounts:dashboard' request.user.id %}">Dashboard</a>
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
        
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login</a>
        <a class="nav-item nav-link active" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
       
    </div>
    
</nav>