accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
	path('others_dashboard/<int:user_id>/', views.others_dashboard, name='others_dashboard'),
	path('profile_update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile_update'),
	path('follow/', views.follow, name='follow'),
	path('unfollow/', views.unfollow, name='unfollow'),
	path('show_photo/<int:pk>/', views.show_photo, name='show_photo'),
	path('update_photo/<int:user_id>/<int:image_id>', views.update_photo, name='update_photo'),
	path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('requests/', views.follow_requests.as_view(), name='requests'),
	path('accept_request/', views.accept_request, name='accept_request'),
	path('follower_list/', views.follower_list.as_view(), name='follower_list'),
	path('reject_follow/', views.reject_follow, name='reject_follow'),

	path('following_list/', views.following_list.as_view(), name='following_list'),
	path('cancel_following/', views.cancel_following, name='cancel_following'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

posts/drf/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post_drf'
urlpatterns = [
    path('posts/', views.AllPosts.as_view() , name='AllPosts'),
    path('<int:post_id>/', views.PostDetail.as_view() , name='PostDetail'),
    path('reply/', views.AddReply.as_view() , name='AddReply'),
    path('comment/', views.AddComment.as_view() , name='AddComment'),
    path('like/<int:post_id>/', views.PostLike.as_view() , name='PostLike'),
    path('<int:post_id>/<int:user_id>/', views.PostLike.as_view() , name='PostLike'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
	path('all_posts/', views.all_posts, name='all_posts'),

	path('<int:year>-<int:month>-<int:day>-<int:post_id>/', views.post_detail, name='post_detail'),
	path('add_post/<int:user_id>/', views.add_post, name='add_post'),
	path('post_delete/<int:user_id>/<int:post_id>/', views.post_delete, name='post_delete'),
	path('post_edit/<int:user_id>/<int:post_id>/', views.post_edit, name='post_edit'),
	path('add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
	path('like/<int:post_id>/', views.post_like, name='post_like'),
	path('dislike/<int:post_id>/', views.post_dislike, name='post_dislike'),

]

socsho/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('single_message/', include('single_message.urls', namespace='single_message')),
    path('', include('home.urls', namespace='home')),
    path('', include('posts.urls', namespace='posts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('search/', include('search.urls', namespace='search')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    
    #django rest framework urls
    path('drf/posts/', include('posts.drf.urls', namespace='post_drf')),
    path('drf/accounts/', include('accounts.drf.urls', namespace='accounts_drf')),
    path('drf/shop/', include('shop.drf.urls', namespace='shop_drf')),


    

]

posts/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
	image = forms.ImageField()

	class Meta:
		model = Post
		fields = ('body', 'image')


class EditPostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('body',)



class AddCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)
		widgets = {
			'body': forms.Textarea(attrs={'class':'form-control'})
		}
		error_messages = {
			'body': {
				'required': 'این فیلد اجباری است',
			}
		}
		help_texts = {
			'body': 'max 400 char'
		}

class AddReplyForm(forms.ModelForm):
		class Meta:
			model = Comment
			fields = ('body',)

posts/drf/views.py
# from urllib import 
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
#from permissions import IsOwnerOrReadOnly
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from django.db.models import Q

from .serializers import PostSerializer, PostCommentsSerializers
from posts.models import Comment, Post, Vote
from accounts.models import Relation


class AllPosts(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self, request):
        # following = Relation.objects.filter(from_user=request.user, accepted=True)
        print (request.user)
        queryset=Post.objects.filter(Q(user=request.user) |
                                     (Q(user__following__from_user=request.user)&
                                     Q(user__following__accepted=True)
                                     )).order_by('-created')
        serializer=PostSerializer(queryset, many=True)
        return Response(serializer.data)

    def post(self,request):
        parser_classes =[MultiPartParser, FormParser]
        srz_data =PostSerializer(data=request.data)
        if srz_data.is_valid():
            slug = slugify(request.data['body'][:30], allow_unicode=True)
            srz_data.save(user=self.request.user, slug=slug)
            return Response(srz_data.data, status=status.HTTP_201_CREATED)
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)


class PostDetail(APIView):
    permission_classes = [IsAuthenticated,]
    def get(self,request,post_id):
        queryset=Post.objects.filter(pk=post_id)
        serializer=PostSerializer(queryset, many=True)
        return Response(serializer.data)

    def delete(self,request, post_id):
        queryset=Post.objects.get(pk=post_id)
        if request.user == queryset.user :
            queryset.delete()
            return Response(status=status.HTTP_204_NO_CONTENT) 
        return Response(status=status.HTTP_400_BAD_REQUEST)

    def put(self,request, post_id):
        parser_classes =[MultiPartParser, FormParser]
        post=Post.objects.get(pk=post_id)
        srz_data = PostSerializer(instance=post, data=request.data, partial=True)
        if srz_data.is_valid():
            if srz_data.validated_data.get('body',None):
                slug = slugify(srz_data.validated_data['body'], allow_unicode=True)
                srz_data.save(slug=slug)
                return Response(srz_data.data, status=status.HTTP_200_OK)
            srz_data.save()
            return Response(srz_data.data, status=status.HTTP_200_OK)
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)


class AddComment(APIView):
    permission_classes = [IsAuthenticated,]

    def post(self,request):
        post=Post.objects.get(pk=request.data['post_id'])
        serializer=PostCommentsSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user, post=post)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self,request):
        comment=Comment.objects.get(pk=request.data['comment_id'])
        if request.user == comment.user :
            comment.delete()
            return Response(status=status.HTTP_204_NO_CONTENT) 
        return Response(status=status.HTTP_400_BAD_REQUEST)

    def put(self,request):
        comment=Comment.objects.get(pk=request.data['comment_id'])
        srz_data = PostCommentsSerializers(instance=comment, data=request.data, partial=True)
        if srz_data.is_valid():
            if srz_data.validated_data.get('body',None):
                slug = slugify(srz_data.validated_data['body'], allow_unicode=True)
                srz_data.save(slug=slug)
                return Response(srz_data.data, status=status.HTTP_200_OK)
            srz_data.save()
            return Response(srz_data.data, status=status.HTTP_200_OK)
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)

class AddReply(APIView):
    permission_classes = [IsAuthenticated,]

    def post(self,request):
        comment=Comment.objects.get(pk=request.data['comment_id'])
        serializer=PostCommentsSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user,post=comment.post, reply=comment, is_reply=True)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PostLike(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self,request,post_id):
        vote=Vote.objects.filter(post__id=post_id, user=request.user).last()
        if vote:
            return Response({'liked':'like'}, status=status.HTTP_200_OK)
        return Response({'liked':'dislike'}, status=status.HTTP_200_OK)

    def post(self,request,post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote(post=post, user=request.user)
        if like:
            like.save()
            return Response({'liked':'like'}, status=status.HTTP_200_OK)
        return Response( status=status.HTTP_400_BAD_REQUEST)

    def delete(self,request,post_id):
        post = get_object_or_404(Post, id=post_id)
        Vote.objects.filter(post=post, user=request.user).delete()
        return Response({'liked':'dislike'}, status=status.HTTP_200_OK)

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify

from django.contrib import messages
# from django.views import View
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
# import redis
# from django.conf import settings
from shop.models import Product, Category
from .models import Post, Comment, Vote
from .forms import AddPostForm, EditPostForm, AddCommentForm, AddReplyForm


def all_posts(request, slug=None):
	posts = Post.objects.all()
	products = Product.objects.filter(available=True)
	categories = Category.objects.filter(is_sub=False)
	if slug:
		category = get_object_or_404(Category, slug=slug)
		products = Product.objects.filter(category=category)
	return render(request, 'posts/all_posts.html', {'products': products, 'categories': categories,'posts': posts})

# redis_con = redis.Redis(settings.REDIS_HOST, settings.REDIS_PORT, settings.REDIS_DB)

def post_detail(request, year, month, day, post_id):
	post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, pk=post_id)
	comments = Comment.objects.filter(post=post, is_reply=False)
	reply_form = AddReplyForm()
	# redis_con.hsetnx('post_views', post.id, 0)

	rviews='note' 	#rviews = redis_con.hincrby('post_views', post.id)
	can_like = False
	if request.user.is_authenticated:
		if post.user_can_like(request.user):
			can_like = True
	if request.method == 'POST':
		form = AddCommentForm(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.post = post
			new_comment.user = request.user
			new_comment.save()
			messages.success(request, 'you comment submitted successfully')
	else:
		form = AddCommentForm()
	return render(request, 'posts/post_detail.html', {'post':post, 'comments':comments, 'form':form, 'reply':reply_form, 'can_like':can_like, 'rviews':rviews})


# class AddPost(LoginRequiredMixin, View ):
# 	form_class = AddPostForm
# 	template_name = 'posts/add_post.html'
#
# 	def get(self, request, user_id):
# 		if request.user.id != user_id:
# 			return redirect('posts:all_posts')
# 		form = self.form_class
# 		return render(request, self.template_name, {'form': form})
#
# 	def post(self, request, user_id):
# 		if request.user.id != user_id:
# 			return redirect('posts:all_posts')
# 		if self.form_class.is_valid():
# 			new_post = self.form_class.save(commit=False)
# 			new_post.user = request.user
# 			new_post.slug = slugify(self.form_class.cleaned_data['body'][:30])
# 			new_post.save()
# 			messages.success(request, 'your post submitted', 'success')
# 			return redirect('accounts:dashboard', user_id)




@login_required
def add_post(request, user_id):
	if request.user.id == user_id:
		if request.method == 'POST':
			form = AddPostForm(request.POST, request.FILES)
			if form.is_valid():
				new_post = form.save(commit=False)
				new_post.user = request.user
				new_post.slug = slugify(form.cleaned_data['body'][:30], allow_unicode=True)
				new_post.save()
				messages.success(request, 'your post submitted', 'success')
				return redirect('accounts:dashboard', user_id)
		else:
			form = AddPostForm()
		return render(request, 'posts/add_post.html', {'form':form})
	else:
		return redirect('posts:all_posts')

@login_required
def post_delete(request, user_id, post_id):
	if user_id == request.user.id:
		Post.objects.filter(pk=post_id).delete()
		messages.success(request, 'your post deleted successfully', 'success')
		return redirect('accounts:dashboard', user_id)
	else:
		return redirect('posts:all_posts')

@login_required
def post_edit(request, user_id, post_id):
	if request.user.id == user_id:
		post = get_object_or_404(Post, pk=post_id)
		if request.method == 'POST':
			form = EditPostForm(request.POST, instance=post)
			if form.is_valid():
				ep = form.save(commit=False)
				ep.slug = slugify(form.cleaned_data['body'][:30])
				ep.save()
				messages.success(request, 'your post edited successfully', 'success')
				return redirect('accounts:dashboard', user_id)
		else:
			form = EditPostForm(instance=post)
		return render(request, 'posts/edit_post.html', {'form':form})
	else:
		return redirect('posts:all_posts')


@login_required
def add_reply(request, post_id, comment_id):
	post = get_object_or_404(Post, id=post_id)
	comment = get_object_or_404(Comment, pk=comment_id)
	if request.method == 'POST':
		form = AddReplyForm(request.POST)
		if form.is_valid():
			reply = form.save(commit=False)
			reply.user = request.user
			reply.post = post
			reply.reply = comment
			reply.is_reply = True
			reply.save()
			messages.success(request, 'your reply submitted successfully', 'success')
	return redirect('posts:post_detail', post.created.year, post.created.month, post.created.day, post.id)


@login_required
def post_like(request, post_id):
	post = get_object_or_404(Post, id=post_id)
	like = Vote(post=post, user=request.user)
	like.save()
	messages.success(request, 'you liked successfully', 'success')
	return redirect('posts:post_detail', post.created.year, post.created.month, post.created.day, post.id)


@login_required
def post_dislike(request, post_id):
	post = get_object_or_404(Post, id=post_id)
	dislike = Vote.objects.filter(post=post, user=request.user).delete()
	messages.success(request, 'you disliked successfully', 'warning')
	return redirect('posts:post_detail', post.created.year, post.created.month, post.created.day, post.id)

posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block title %} {{ request.user.username }} add post {% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Post" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/all_posts.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %} Home {% endblock %}

{% block content %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Posts</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Product</a>
        </li>
       
        
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% for post in posts %}
                <div class="card" style="width: 18rem; display:flex; flex_wrap:wrap; ">
                    {% thumbnail post.image "300x300" as img %}
                        <img src="{{ img.url }}" class="card-img-top">
                    {% endthumbnail %}
                    <p class="card-body">
                        <a href="{% url 'accounts:dashboard' post.user.id %}">
                            {{ post.user }}:
                        </a>
                        <a style="color:darkgrey" href="{{ post.get_absolute_url }}">
                            {{ post.body }}
                        </a>
                    </p>
                </div><br/>
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            {% for category in categories %}

                <div class="btn-group">
                    <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
                    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    <div class="dropdown-menu">
                        {% for sub in category.scategory.all %}
                            <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <br/><br/><br/>

            {% for product in products %}
                <div class="card" style="width: 18rem; display:inline-block">
                    {% thumbnail product.image "300x300" as img %}
                    <img src="{{ img.url }}" class="card-img-top">
                    {% endthumbnail %}
                    <div class="card-body">
                        <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
                    </div>
                </div>
            {% endfor %}    
        </div>
        
    </div>
    
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %} Edit Post {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block js_files %}
<script>
    $(document).ready(function(){
      $(".Reply_class").click(function(){
        $(this).parent().next().toggle();
       });
      
    });
</script>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated and request.user.id == post.user.id%}
        <a href="{% url 'posts:post_delete' post.user.id post.id %}">delete post</a>
        <a href="{% url 'posts:post_edit' post.user.id post.id %}">Edit post</a>
    {% endif %}
    <p>{{ post.user }} | {{ post.created|date }} | {{ rviews }} views</p>
    <p>{{ post.body }}</p><hr/>

    {% with total=comments.count %}
        <p>This post has {{ total }} comment{{ total|pluralize }}</p>
    {% endwith %}

    {% if request.user.is_authenticated %}
        {% if not can_like %}
            <a href="{% url 'posts:post_like' post.id  %}" class="btn btn-primary {% if can_like %}disabled {% endif %} col-md-2">Like {{ post.likes_count }}</a>
        {% else %}
            <div class="btn btn-primary col-md-3">You Liked and {{ post.likes_count }} others</div>
            <div><a href="{% url 'posts:post_dislike' post.id  %}" class="btn btn-warning  col-md-1">DissLike </a>
            </div>
        {% endif %}   
    {% endif %}
<br/><br/><br/>

    {% if request.user.is_authenticated %}
    <form action="" method="post" novalidate class="col-md-6">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
    {% else %}
        <p>only logged in users can send comments</p>
    {% endif %}<br/><br/><br/>

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-body">{{ comment.body }}</p>
            {% if request.user.is_authenticated %}
                <div  class="card-header"><a href="{% url 'accounts:dashboard' comment.user.id  %}"> {{comment.user }} </a><div  class="Reply_class btn btn-primary col-md-1">reply</div></div>

                <div id="reply_form" class="card-body" style="display:none">
                    <form action="{% url 'posts:add_reply' post.id comment.id %}" method="post">
                        {% csrf_token %}
                        {{ reply.as_p }}
                        <input type="submit" value="Send">
                    </form>
                </div>
            {% else %}
                <p>you have to login to send reply</p>
            {% endif %}
            {% for reply in comment.rcomment.all %}
                <p class="bg-primary text-white p-3 m-5">{{ reply.user }} <br/> {{ reply.body }}</p>
            {% endfor %}
        </div><br/>
    {% empty %}
        <p>There is no comment</p>
    {% endfor %}
{% endblock %}